# These are supported funding model platforms

erc20: 0xC0602Fae5Cb54157d427f7511Cce72753A9BDE16 # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
bsc20: 0xC0602Fae5Cb54157d427f7511Cce72753A9BDE16 # Replace with a single Patreon username
