# These are supported funding model platforms

github: [GarudaProject]
patreon: rsalman
open_collective: # Replace with a single Open Collective username
ko_fi: rsalman
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['0xC0602Fae5Cb54157d427f7511Cce72753A9BDE16']
